// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBNSEGRHr-p21YNj3W2TKbc0Ly6Zu1vWnQ',
    appId: '1:1052584781367:web:5aee9baaeb5b4a294441b2',
    messagingSenderId: '1052584781367',
    projectId: 'tebbyprojects-73237',
    authDomain: 'tebbyprojects-73237.firebaseapp.com',
    storageBucket: 'tebbyprojects-73237.firebasestorage.app',
    measurementId: 'G-C99LRN5RS1',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyA7eEKmA-y8412I0IVpY2sO7jgBAY0LAh0',
    appId: '1:1052584781367:android:c05b3ca173de57834441b2',
    messagingSenderId: '1052584781367',
    projectId: 'tebbyprojects-73237',
    storageBucket: 'tebbyprojects-73237.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCIDvse4hWN2pjbLGRe-ad8_fqnZ6_-zMQ',
    appId: '1:1052584781367:ios:cdbd4514dc2a2fbc4441b2',
    messagingSenderId: '1052584781367',
    projectId: 'tebbyprojects-73237',
    storageBucket: 'tebbyprojects-73237.firebasestorage.app',
    iosBundleId: 'com.example.wallpaper',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCIDvse4hWN2pjbLGRe-ad8_fqnZ6_-zMQ',
    appId: '1:1052584781367:ios:cdbd4514dc2a2fbc4441b2',
    messagingSenderId: '1052584781367',
    projectId: 'tebbyprojects-73237',
    storageBucket: 'tebbyprojects-73237.firebasestorage.app',
    iosBundleId: 'com.example.wallpaper',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBNSEGRHr-p21YNj3W2TKbc0Ly6Zu1vWnQ',
    appId: '1:1052584781367:web:417996a6bd98924c4441b2',
    messagingSenderId: '1052584781367',
    projectId: 'tebbyprojects-73237',
    authDomain: 'tebbyprojects-73237.firebaseapp.com',
    storageBucket: 'tebbyprojects-73237.firebasestorage.app',
    measurementId: 'G-HX726PJ4GG',
  );
}
